### PR TITLE
upgrade rai to latest

### PR DESCRIPTION
**Pull request by NRHelmi**
Upgrade `rai-cli` to use latest from `rai-sdk-go` (version: `v0.3.1-alpha`)

### CODE REVIEW

**Comment by andy-dean-rai** [comment]
Is it the case that only go.mod had to be manually edited, and all the other file differences are generated?

**Comment by NRHelmi** [comment]
> Is it the case that only go.mod had to be manually edited, and all the other file differences are generated?

Yep that's the case, I remember there is a go command to automatically update a specific dep/deps
Please make sure to always check the latest dep from [pkg.go.dev](https://pkg.go.dev/github.com/relationalai/rai-sdk-go?tab=versions) :pray:

**Review by andy-dean-rai — APPROVED** [review]
Looks good to me.

**Comment by cpetitpas** [comment]
After `pull`, `./tidy`, and `./make` testing reveals that the issue with `missing` (see https://github.com/RelationalAI/rai-cli/pull/17#issuecomment-1217167668 - "json: cannot unmarshal object into Go struct field RelKey.output.rel_key.values of type string") no longer occurs.
However, as detailed in https://github.com/RelationalAI/rai-sdk-go/issues/31, we still have output issues.
For me, the quotes missing around `string` types is the biggest issue. Due to how my editor formats (colors), the result is that the output is more difficult to read.
Thanks @NRHelmi .

**Pull request merged**
