### PR TITLE
upgrade to v2 transactions

### LINKED ISSUE #16: migrate to v2 transactions
The CLI appears to still use v1 transactions. The Go SDK now supports V2; let's migrate.

### PR DESCRIPTION
**Pull request by vilterp**
Closes #16 

Results should look the same.

### CODE REVIEW

**Comment by vilterp** [comment]
btw, @NHDaly, it looks like the CLI dumps the response object to stdout as JSON: https://github.com/RelationalAI/rai-cli/blob/068c47fc3c511838828ea28c437c68d203ff2813/rai/cmds.go#L149-L153

I think this is explains what we were seeing in https://github.com/RelationalAI/raicode/issues/9128: it's the Go JSON encoder which decides to marshal byte arrays to JSON as base64 strings: https://pkg.go.dev/encoding/json#Marshal:~:text=Array%20and%20slice%20values%20encode%20as%20JSON%20arrays%2C%20except%20that%20%5B%5Dbyte%20encodes%20as%20a%20base64%2Dencoded%20string%2C

**Comment by NHDaly** [comment]
🤯 great find, @vilterp!! Can you copy/link that comment over on the other issue? Excellent find. 👍 👍 makes sense! :)

**Comment by NHDaly** [comment]
@vilterp if you look at `exec -h`, there's already a flag for the output format:
```
rai exec -h
Execute a transaction on the given database

Usage:
  rai exec database [flags]

Flags:
  -c, --code string     rel source code
  -e, --engine string   default engine
  -f, --file string     rel source file
  -h, --help            help for exec
      --readonly        transaction is read-only

Global Flags:
      --config string    config file (default "~/.rai/config")
      --format string    format results, 'json' or 'pretty' (default "pretty")
      --host string      host name
      --port string      port number
      --profile string   config profile (default "default")
  -q, --quiet            silence status output
```

+1 to defaulting to the pretty-printing, like we currently do. Maybe we can _also_ print the transaction details before printing the results? Maybe just a subset of the transaction details?

**Comment by vilterp** [comment]
Hm yeah… I'm not sure why it's printing as JSON instead of pretty; I didn't explicitly change that. Maybe it was looking for a specific format in the output that it's no longer getting, and it's defaulting to JSON. Will have to read that code path a bit more.

**Comment by NHDaly** [comment]
I guess the logic to pretty-print the results of a v2 transaction probably isn't written yet.

This is similar to the https://github.com/RelationalAI/rai-sdk-julia/issues/38 PR that @NRHelmi put together for the julia SDK: when you switch to the new structure of the data, we have to rewrite the rendering code, since you're getting back a different structure.

**Comment by vilterp** [comment]
Yep. Maybe I can mimic what you guys did there

**Comment by vilterp** [comment]
@cpetitpas I won't merge this until we fix pretty printing. The breakage you filed in https://github.com/RelationalAI/rai-cli/issues/20#issuecomment-1190768803 was unrelated to this PR and has been fixed now, as explained there.

**Comment by NHDaly** [comment]
I am removing the reviewers until this has support for pretty-printing again

**Comment by vilterp** [comment]
Thanks Helmi! Let me build locally and give it a try…

**Comment by vilterp** [comment]
Looks good!

```
$ build/rai exec pv-test -c '2+2' -e 'dg-test'
Executing query (pv-test/dg-test) readonly=false .. Ok (0.5s)
/:output/Int64
4
```

With JSON format:

```
build/rai exec pv-test -c '2+2' -e 'dg-test' --format json
Executing query (pv-test/dg-test) readonly=false .. Ok (0.3s)
{
  "GotCompleteResult": true,
  "Transaction": {
    "id": "873bf34c-66bf-dd6b-ec34-a027df1a4be7",
    "state": "COMPLETED"
  },
  "Results": [
    {
      "RelationID": "/:output/Int64",
      "Table": [
        [
          4
        ]
      ]
    }
  ],
  "Metadata": {
    "relations": [
      {
        "relation_id": {
          "arguments": [
            {
              "tag": 3,
              "constant_type": {
                "rel_type": {
                  "tag": 1,
                  "primitive_type": 17
                },
                "value": {
                  "arguments": [
                    {
                      "tag": 17,
                      "Value": {
                        "StringVal": "b3V0cHV0"
                      }
                    }
                  ]
                }
              }
            },
            {
              "tag": 1,
              "primitive_type": 2
            }
          ]
        },
        "file_name": "0.arrow"
      }
    ]
  },
  "Problems": []
}
```

I see it in the txn log: https://console.relationalai.com/relationalai-team-rd-ux/transactions/873bf34c-66bf-dd6b-ec34-a027df1a4be7
image

@hersker13 I know you were saying you use the CLI with JQ; will this change break your workflow? I think maybe you'd been using a build that only printed JSON, because of this little snafu: https://github.com/RelationalAI/rai-cli/issues/20#issuecomment-1190768803 Hopefully having the option will work for you.

Otherwise, I can't approve my own PR now that you've taken it over Helmi, but I think this is good to go.

**Review by NHDaly — APPROVED** [review]
🎉 thanks both, LGTM! :) 👍 🚀

**Review by NHDaly — CHANGES_REQUESTED** [review]
I'm blocking this PR until https://github.com/RelationalAI/rai-sdk-go/issues/20#issuecomment-1210097348 has been addressed.

As-is, i'm pretty sure this will cause all long transactions to start failing in the CLI.

> Oh, @NRHelmi, we **need** to fix this before merging [RelationalAI/rai-cli#17](https://github.com/RelationalAI/rai-cli/pull/17), otherwise all transactions longer than 10 seconds will appear to time out at the CLI! 😮

**Review by NHDaly — APPROVED** [review]
Awesome, from discussion on #20, it sounds like we misunderstood the situation.

So this PR should be good to go, again! 👍 Merge away, I say.

Thanks @NRHelmi and @vilterp! 😊

**Comment by vilterp** [comment]
Cool. Pretty satisfied that this works from my testing above; gonna merge. Thanks for taking it the rest of the way @NRHelmi!

**Comment by cpetitpas** [comment]
Nice! After pull, `./tidy`, `./make` all seems fine using RAI build https://hydra.dev.relational.ai/eval/177859 (8/16/2022).
Before pulling and rebuilding:
```
def r = (1,missing)
def output = l : #(r[l])
```
....produced:
```
json: cannot unmarshal object into Go struct field RelKey.output.rel_key.values of type string
```
After:
```
chris@PetitpasServer:~/Documents/RAI$ rai exec cp-testing0816 -e cp-0816 -f tests/specializeMissing.rel
Executing query (cp-testing0816/cp-0816) readonly=false .. Ok (1.8s)
/:output/Int64/Missing(missing)
1

```

`--format pretty` and `--format json` also seem fine.
Thanks @vilterp / @NHDaly / @NRHelmi !

**Pull request merged**
